package com.fptu.group1.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class representing a brand in the ElectroShop system.
 * Maps to the 'Brands' table in the 'ElectroShop' schema.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Getter
@Setter
@Table(name = "Brands", schema = "dbo")
public class Brand {

    // Unique identifier for the brand, auto-generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "brand_id")
    private Long brandId;

    // The brand's name. Must be unique.
    @Column(name = "name", nullable = false, unique = true, length = 100)
    private String name;

    // Detailed description of the brand.
    @Column(name = "description", columnDefinition = "nvarchar(max)")
    private String description;

    // Country of origin for the brand.
    @Column(name = "country", length = 100)
    private String country;

    // Year the brand was founded.
    @Column(name = "founded_year")
    private Integer foundedYear;

    // Official website URL of the brand.
    @Column(name = "website", length = 255)
    private String website;
}

