package com.fptu.group1.model;

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class representing a cart item in the ElectroShop system.
 * Maps to the 'Cart' table in the 'ElectroShop' schema.
 * Represents items added to a user's shopping cart.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Getter
@Setter
@Table(name = "Cart", schema = "dbo")
public class Cart {

    // Unique identifier for the cart item, auto-generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "cart_id", columnDefinition = "int")
    private Long cartId;

    // Reference to the user who owns this cart item.
    @Column(name = "user_id", nullable = false, columnDefinition = "int")
    private Long userId;

    // User entity relationship.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
    private User user;

    // Reference to the product variant in the cart.
    @Column(name = "variant_id", nullable = false, columnDefinition = "int")
    private Long variantId;

    // Product variant entity relationship.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "variant_id", nullable = false, insertable = false, updatable = false)
    private ProductVariant variant;

    // Quantity of the variant in the cart.
    @Column(name = "quantity", nullable = false)
    @Builder.Default
    private Integer quantity = 1;

    // Date and time when the item was added to the cart.
    @Column(name = "added_at", nullable = false)
    private LocalDateTime addedAt;
}

