package com.fptu.group1.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class representing a product comment in the ElectroShop system.
 * Maps to the 'Comments' table in the 'ElectroShop' schema.
 * Supports nested comments through self-reference (parent_comment_id).
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Getter
@Setter
@Table(name = "Comments", schema = "dbo")
public class Comment {

    // Unique identifier for the comment, auto-generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "comment_id")
    private Long commentId;

    // Reference to the product this comment belongs to.
    @Column(name = "product_id", nullable = false)
    private Long productId;

    // Product entity relationship.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false, insertable = false, updatable = false)
    private Product product;

    // Reference to the user who wrote the comment.
    @Column(name = "user_id", nullable = false)
    private Long userId;

    // User entity relationship.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
    private User user;

    // Reference to the parent comment (for nested/reply comments).
    @Column(name = "parent_comment_id")
    private Long parentCommentId;

    // Parent comment entity (self-reference).
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parent_comment_id", insertable = false, updatable = false)
    private Comment parent;

    // Child comments (replies).
    @OneToMany(mappedBy = "parent", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<Comment> replies = new ArrayList<>();

    // The comment content.
    @Column(name = "content", nullable = false, length = 1000)
    private String content;

    // Date and time when the comment was created.
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    // Whether the comment is soft-deleted.
    @Column(name = "is_deleted", nullable = false)
    @Builder.Default
    private Boolean isDeleted = false;
}

