package com.fptu.group1.model;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class representing an order in the ElectroShop system.
 * Maps to the 'Orders' table in the 'ElectroShop' schema.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Getter
@Setter
@Table(name = "Orders", schema = "dbo")
public class Order {

    // Unique identifier for the order, auto-generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "order_id")
    private Long orderId;

    // Reference to the user who placed the order.
    @Column(name = "user_id")
    private Long userId;

    // User entity relationship.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", insertable = false, updatable = false)
    private User user;

    // Total price of the order.
    @Column(name = "total_price", nullable = false, precision = 18, scale = 2)
    private BigDecimal totalPrice;

    // Shipping address for the order.
    @Column(name = "shipping_address", length = 500)
    private String shippingAddress;

    // Date and time when the order was created.
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    // Reference to the order status.
    @Column(name = "status_id", nullable = false)
    private Long statusId;

    // Order status entity relationship.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "status_id", nullable = false, insertable = false, updatable = false)
    private OrderStatus status;

    // Optional note for the order.
    @Column(name = "note", length = 1000)
    private String note;

    // Reference to the voucher used (if any).
    @Column(name = "voucher_id")
    private Long voucherId;

    // Voucher entity relationship.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "voucher_id", insertable = false, updatable = false)
    private Voucher voucher;

    // Order details (items in the order).
    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<OrderDetail> orderDetails = new ArrayList<>();

    // Payments for this order.
    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<Payment> payments = new ArrayList<>();
}

