package com.fptu.group1.model;

import java.util.ArrayList;
import java.util.List;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class representing an order status in the ElectroShop system.
 * Maps to the 'OrderStatus' table in the 'ElectroShop' schema.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Getter
@Setter
@Table(name = "OrderStatus", schema = "dbo")
public class OrderStatus {

    // Unique identifier for the status, auto-generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "status_id", columnDefinition = "int")
    private Long statusId;

    // The status name. Must be unique.
    @Column(name = "status_name", nullable = false, unique = true, length = 50)
    @Enumerated(EnumType.STRING)
    private OrderStatusName statusName;

    // Orders with this status.
    @OneToMany(mappedBy = "status", fetch = jakarta.persistence.FetchType.LAZY)
    @Builder.Default
    private List<Order> orders = new ArrayList<>();

    /**
     * Enum representing order status names in the system.
     */
    public enum OrderStatusName {
        PENDING,
        CONFIRMED,
        PROCESSING,
        SHIPPED,
        DELIVERED,
        CANCELLED,
        REFUNDED
    }
}

