package com.fptu.group1.model;

import java.math.BigDecimal;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class representing an order detail (line item) in the ElectroShop system.
 * Maps to the 'OrderDetails' table in the 'ElectroShop' schema.
 * Represents a single product variant in an order.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Getter
@Setter
@Table(name = "OrderDetails", schema = "dbo")
public class OrderDetail {

    // Unique identifier for the order detail, auto-generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "order_detail_id", columnDefinition = "int")
    private Long orderDetailId;

    // Reference to the order this detail belongs to.
    @Column(name = "order_id", nullable = false, columnDefinition = "int")
    private Long orderId;

    // Order entity relationship.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "order_id", nullable = false, insertable = false, updatable = false)
    private Order order;

    // Reference to the product variant ordered.
    @Column(name = "variant_id", nullable = false, columnDefinition = "int")
    private Long variantId;

    // Product variant entity relationship.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "variant_id", nullable = false, insertable = false, updatable = false)
    private ProductVariant variant;

    // Quantity of the variant ordered.
    @Column(name = "quantity", nullable = false)
    private Integer quantity;

    // Unit price at the time of order.
    @Column(name = "unit_price", nullable = false, precision = 18, scale = 2)
    private BigDecimal unitPrice;

    // Warranty period in months.
    @Column(name = "warranty_months", nullable = false)
    @Builder.Default
    private Integer warrantyMonths = 0;
}

