package com.fptu.group1.model;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class representing a payment in the ElectroShop system.
 * Maps to the 'Payments' table in the 'ElectroShop' schema.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Getter
@Setter
@Table(name = "Payments", schema = "dbo")
public class Payment {

    // Unique identifier for the payment, auto-generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "payment_id")
    private Long paymentId;

    // Reference to the order this payment belongs to.
    @Column(name = "order_id", nullable = false)
    private Long orderId;

    // Order entity relationship.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "order_id", nullable = false, insertable = false, updatable = false)
    private Order order;

    // Payment method used (e.g., "CREDIT_CARD", "PAYPAL", "BANK_TRANSFER").
    @Column(name = "payment_method", nullable = false, length = 50)
    private String paymentMethod;

    // Payment status (e.g., "PENDING", "COMPLETED", "FAILED", "REFUNDED").
    @Column(name = "payment_status", nullable = false, length = 50)
    private String paymentStatus;

    // Transaction reference from payment gateway.
    @Column(name = "transaction_reference", length = 200)
    private String transactionReference;

    // Date and time when the payment was completed.
    @Column(name = "paid_at")
    private LocalDateTime paidAt;

    // Payment amount.
    @Column(name = "amount", nullable = false, precision = 18, scale = 2)
    private BigDecimal amount;
}

