package com.fptu.group1.model;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class representing a product in the ElectroShop system.
 * Maps to the 'Products' table in the 'ElectroShop' schema.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Getter
@Setter
@Table(name = "Products", schema = "dbo")
public class Product {

    // Unique identifier for the product, auto-generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "product_id", columnDefinition = "int")
    private Long productId;

    // The product's name.
    @Column(name = "name", nullable = false, length = 255)
    private String name;

    // URL-friendly slug for the product.
    @Column(name = "slug", length = 255)
    private String slug;

    // Short description of the product.
    @Column(name = "short_description", length = 512)
    private String shortDescription;

    // Detailed description of the product.
    @Column(name = "description", columnDefinition = "nvarchar(max)")
    private String fullDescription;

    // Reference to the brand this product belongs to.
    @Column(name = "brand_id", columnDefinition = "int")
    private Long brandId;

    // Brand entity relationship.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "brand_id", insertable = false, updatable = false)
    private Brand brand;

    // Reference to the category this product belongs to.
    @Column(name = "category_id", columnDefinition = "int")
    private Long categoryId;

    // Category entity relationship.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id", insertable = false, updatable = false)
    private Category category;

    // Whether the product is soft-deleted.
    @Column(name = "is_deleted", nullable = false)
    @Builder.Default
    private Boolean isDeleted = false;

    // Date and time when the product was created.
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    // Date and time when the product was last updated.
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    // Model number of the product.
    @Column(name = "model_number", length = 100)
    private String modelNumber;

    // Year the product was released.
    @Column(name = "release_year")
    private Integer releaseYear;

    // Default price of the product.
    @Column(name = "default_price", precision = 18, scale = 2)
    private BigDecimal defaultPrice;

    // Main image URL of the product.
    @Column(name = "image_url", length = 500)
    private String imageUrl;

    // Product variants (different sizes, colors, etc.).
    @OneToMany(mappedBy = "product", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<ProductVariant> variants = new ArrayList<>();

    // Product specifications (key-value pairs).
    @OneToMany(mappedBy = "product", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<ProductSpecification> specifications = new ArrayList<>();

    // Ratings for this product.
    @OneToMany(mappedBy = "product", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<Rating> ratings = new ArrayList<>();

    // Comments for this product.
    @OneToMany(mappedBy = "product", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<Comment> comments = new ArrayList<>();

    // Promotions that include this product.
    @OneToMany(mappedBy = "product", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<PromotionProduct> promotionProducts = new ArrayList<>();
}

