package com.fptu.group1.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class representing a product specification in the ElectroShop system.
 * Maps to the 'ProductSpecifications' table in the 'ElectroShop' schema.
 * Stores key-value pairs of product specifications (e.g., "Screen Size": "15.6 inches").
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Getter
@Setter
@Table(name = "ProductSpecifications", schema = "dbo")
public class ProductSpecification {

    // Unique identifier for the specification, auto-generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "spec_id")
    private Long specId;

    // Reference to the product this specification belongs to.
    @Column(name = "product_id", nullable = false)
    private Long productId;

    // Product entity relationship.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false, insertable = false, updatable = false)
    private Product product;

    // The specification key (e.g., "Screen Size", "RAM", "Storage").
    @Column(name = "spec_key", nullable = false, length = 150)
    private String specKey;

    // The specification value (e.g., "15.6 inches", "16GB", "512GB SSD").
    @Column(name = "spec_value", length = 500)
    private String specValue;
}

