package com.fptu.group1.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class representing a product variant in the ElectroShop system.
 * Maps to the 'ProductVariants' table in the 'ElectroShop' schema.
 * A variant represents different options of a product (e.g., size, color, storage).
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Getter
@Setter
@Table(name = "ProductVariants", schema = "dbo")
public class ProductVariant {

    // Unique identifier for the variant, auto-generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "variant_id", columnDefinition = "int")
    private Long variantId;

    // Reference to the product this variant belongs to.
    @Column(name = "product_id", nullable = false, columnDefinition = "int")
    private Long productId;

    // Product entity relationship.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false, insertable = false, updatable = false)
    private Product product;

    // Stock Keeping Unit (SKU) for the variant. Must be unique.
    @Column(name = "sku", unique = true, length = 100)
    private String sku;

    // Attributes of the variant (e.g., "Color: Red, Size: Large").
    @Column(name = "attributes", length = 500)
    private String attributes;

    // Price of this variant.
    @Column(name = "price", nullable = false, precision = 18, scale = 2)
    private BigDecimal price;

    // Current stock quantity.
    @Column(name = "stock", nullable = false)
    @Builder.Default
    private Integer stock = 0;

    // Whether the variant is currently active/available.
    @Column(name = "is_active", nullable = false)
    @Builder.Default
    private Boolean isActive = true;

    // Cart items for this variant.
    @OneToMany(mappedBy = "variant", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<Cart> cartItems = new ArrayList<>();

    // Order details for this variant.
    @OneToMany(mappedBy = "variant", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<OrderDetail> orderDetails = new ArrayList<>();
}

