package com.fptu.group1.model;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class representing a promotion in the ElectroShop system.
 * Maps to the 'Promotions' table in the 'ElectroShop' schema.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Getter
@Setter
@Table(name = "Promotions", schema = "dbo")
public class Promotion {

    // Unique identifier for the promotion, auto-generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "promotion_id")
    private Long promotionId;

    // The promotion's name.
    @Column(name = "name", nullable = false, length = 150)
    private String name;

    // Description of the promotion.
    @Column(name = "description", length = 1000)
    private String description;

    // Discount type (e.g., "fixed", "percent").
    @Column(name = "discount_type", nullable = false, length = 20)
    private String discountType;

    // Discount value (amount or percentage).
    @Column(name = "discount_value", nullable = false, precision = 18, scale = 2)
    private BigDecimal discountValue;

    // Start date and time of the promotion.
    @Column(name = "start_date", nullable = false)
    private LocalDateTime startDate;

    // End date and time of the promotion.
    @Column(name = "end_date", nullable = false)
    private LocalDateTime endDate;

    // Whether the promotion is currently active.
    @Column(name = "is_active", nullable = false)
    @Builder.Default
    private Boolean isActive = true;

    // Date and time when the promotion was created.
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    // Date and time when the promotion was last updated.
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    // Products included in this promotion (many-to-many relationship).
    @OneToMany(mappedBy = "promotion", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<PromotionProduct> promotionProducts = new ArrayList<>();
}

