package com.fptu.group1.model;

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class representing a product rating in the ElectroShop system.
 * Maps to the 'Ratings' table in the 'ElectroShop' schema.
 * Each user can rate a product only once (unique constraint on user_id + product_id).
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Getter
@Setter
@Table(name = "Ratings", schema = "dbo", 
       uniqueConstraints = @UniqueConstraint(name = "UQ_Ratings_UserProduct", columnNames = {"user_id", "product_id"}))
public class Rating {

    // Unique identifier for the rating, auto-generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "rating_id")
    private Long ratingId;

    // Reference to the user who gave the rating.
    @Column(name = "user_id", nullable = false)
    private Long userId;

    // User entity relationship.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
    private User user;

    // Reference to the product being rated.
    @Column(name = "product_id", nullable = false)
    private Long productId;

    // Product entity relationship.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false, insertable = false, updatable = false)
    private Product product;

    // Rating value (1-5).
    @Column(name = "rating", nullable = false)
    private Integer ratingValue;

    // Optional review text accompanying the rating.
    @Column(name = "review", length = 1000)
    private String review;

    // Date and time when the rating was created.
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;
}

