package com.fptu.group1.model;

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class representing a token in the ElectroShop system.
 * Maps to the 'Tokens' table in the 'ElectroShop' schema.
 * Used for password reset, email verification, and other token-based operations.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Getter
@Setter
@Table(name = "Tokens", schema = "dbo")
public class Token {

    // Unique identifier for the token, auto-generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "token_id")
    private Long tokenId;

    // Reference to the user this token belongs to.
    @Column(name = "user_id", nullable = false)
    private Long userId;

    // User entity relationship.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
    private User user;

    // The token string value.
    @Column(name = "token", nullable = false, length = 255)
    private String tokenValue;

    // Type of token (e.g., "RESET_PASSWORD", "EMAIL_VERIFICATION").
    @Column(name = "token_type", nullable = false, length = 50)
    private String tokenType;

    // Date and time when the token expires.
    @Column(name = "expiry_time", nullable = false)
    private LocalDateTime expiryTime;

    // Whether the token has been used.
    @Column(name = "is_used", nullable = false)
    @Builder.Default
    private Boolean isUsed = false;

    // Date and time when the token was created.
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;
}

