package com.fptu.group1.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class representing a user in the ElectroShop system.
 * Maps to the 'Users' table in the 'ElectroShop' schema.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Getter
@Setter
@Table(name = "Users", schema = "dbo")
public class User {

    // Unique identifier for the user, auto-generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "user_id")
    private Long userId;

    // The user's full name.
    @Column(name = "name", nullable = false, length = 100)
    private String name;

    // Unique username used for login.
    @Column(name = "username", unique = true, length = 255)
    private String username;

    // Hashed password string.
    @Column(name = "password_hash", length = 255)
    private String passwordHash;

    // Phone number of the user.
    @Column(name = "phone", length = 20)
    private String phone;

    // Email address of the user. Must be unique.
    @Column(name = "email", unique = true, length = 100)
    private String email;

    // Reference to the user's role.
    @Column(name = "role_id", nullable = false)
    private Long roleId;

    // Role entity relationship.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "role_id", nullable = false, insertable = false, updatable = false)
    private Role role;

    // Date and time when the user registered or was created.
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    // The user's shipping/delivery address.
    @Column(name = "shipping_address", length = 255)
    private String shippingAddress;

    // Whether the user account is banned.
    @Column(name = "is_banned", nullable = false)
    @Builder.Default
    private Boolean isBanned = false;

    // URL to the user's avatar image.
    @Column(name = "avatar_url", length = 255)
    private String avatarUrl;

    // Ratings given by this user.
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<Rating> ratings = new ArrayList<>();

    // Comments made by this user.
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<Comment> comments = new ArrayList<>();

    // Cart items for this user.
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<Cart> cartItems = new ArrayList<>();

    // Orders placed by this user.
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<Order> orders = new ArrayList<>();

    // Tokens for this user.
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<Token> tokens = new ArrayList<>();
}
