package com.fptu.group1.model;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class representing a voucher in the ElectroShop system.
 * Maps to the 'Vouchers' table in the 'ElectroShop' schema.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Getter
@Setter
@Table(name = "Vouchers", schema = "dbo")
public class Voucher {

    // Unique identifier for the voucher, auto-generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "voucher_id")
    private Long voucherId;

    // Voucher code. Must be unique.
    @Column(name = "code", nullable = false, unique = true, length = 50)
    private String code;

    // Description of the voucher.
    @Column(name = "description", length = 255)
    private String description;

    // Discount type (e.g., "FIXED", "PERCENT").
    @Column(name = "discount_type", nullable = false, length = 20)
    private String discountType;

    // Discount amount or percentage value.
    @Column(name = "discount_amount", nullable = false, precision = 18, scale = 2)
    private BigDecimal discountAmount;

    // Minimum order value required to use this voucher.
    @Column(name = "min_order_value", precision = 18, scale = 2)
    private BigDecimal minOrderValue;

    // Start date when the voucher becomes valid.
    @Column(name = "start_date", nullable = false)
    private LocalDate startDate;

    // Expiry date when the voucher becomes invalid.
    @Column(name = "expiry_date", nullable = false)
    private LocalDate expiryDate;

    // Maximum number of times this voucher can be used.
    @Column(name = "usage_limit")
    private Integer usageLimit;

    // Date and time when the voucher was created.
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    // Orders that used this voucher.
    @OneToMany(mappedBy = "voucher", fetch = jakarta.persistence.FetchType.LAZY)
    @Builder.Default
    private List<Order> orders = new ArrayList<>();
}

