import type {
  Product,
  User,
  Comment,
  Promotion,
  Order,
  Address,
  Voucher,
  FAQ,
  Brand,
  Category,
  SupportTicket,
} from "./types"

export const mockBrands: Brand[] = [
  { id: "brand1", name: "Apple" },
  { id: "brand2", name: "Samsung" },
  { id: "brand3", name: "Sony" },
  { id: "brand4", name: "Dell" },
  { id: "brand5", name: "Xiaomi" },
]

export const mockCategories: Category[] = [
  { id: "cat1", name: "Smartphones", description: "Latest mobile phones and devices" },
  { id: "cat2", name: "Tablets", description: "Portable computing devices" },
  { id: "cat3", name: "Accessories", description: "Cases, chargers, and more" },
  { id: "cat4", name: "Computers", description: "Laptops and desktop computers" },
  { id: "cat5", name: "Wearables", description: "Smartwatches and fitness trackers" },
]

export const mockAddresses: Address[] = [
  {
    id: "addr1",
    fullName: "John Doe",
    address: "123 Main Street, Apt 4B",
    phone: "0901234567",
    city: "Ho Chi Minh City",
    district: "District 1",
    ward: "Ward 1",
    isDefault: true,
  },
  {
    id: "addr2",
    fullName: "John Doe",
    address: "456 Secondary Ave, Suite 100",
    phone: "0901234567",
    city: "Hanoi",
    district: "Ba Dinh",
    ward: "Ward 5",
    isDefault: false,
  },
]

export const mockVouchers: Voucher[] = [
  {
    id: "vouch1",
    code: "GIAM10",
    discountPercent: 10,
    description: "10% discount on all orders",
    active: true,
  },
  {
    id: "vouch2",
    code: "SALE100K",
    discountAmount: 100000,
    description: "Flat 100K discount",
    active: true,
  },
  {
    id: "vouch3",
    code: "SUMMER30",
    discountPercent: 30,
    description: "Summer sale - 30% off",
    active: true,
  },
  {
    id: "vouch4",
    code: "FIRSTBUY",
    discountPercent: 15,
    description: "First time buyer - 15% off",
    active: true,
  },
]

export const mockFAQs: FAQ[] = [
  {
    id: "faq1",
    question: "Giao hàng trong bao lâu?",
    answer: "Chúng tôi giao hàng trong 2-5 ngày toàn quốc. Hà Nội và TP.HCM giao trong 1-2 ngày.",
    category: "Shipping",
  },
  {
    id: "faq2",
    question: "Có chính sách hoàn trả không?",
    answer: "Có, bạn có thể hoàn trả sản phẩm trong 30 ngày nếu chưa sử dụng.",
    category: "Returns",
  },
  {
    id: "faq3",
    question: "Bảo hành sản phẩm bao lâu?",
    answer: "Tất cả sản phẩm đều có bảo hành chính hãng từ 12-24 tháng.",
    category: "Warranty",
  },
  {
    id: "faq4",
    question: "Có hỗ trợ 24/7 không?",
    answer: "Có, đội hỗ trợ khách hàng của chúng tôi hoạt động 24/7.",
    category: "Support",
  },
  {
    id: "faq5",
    question: "Tôi có thể theo dõi đơn hàng không?",
    answer: "Có, bạn sẽ nhận mã theo dõi qua email sau khi đơn hàng được vận chuyển.",
    category: "Tracking",
  },
]

export const mockSupportTickets: SupportTicket[] = [
  {
    id: "ticket1",
    userId: "user1",
    subject: "Tôi chưa nhận được đơn hàng",
    message: "Tôi đặt hàng 3 ngày trước nhưng vẫn chưa nhận được. Mã đơn hàng: #order1",
    status: "open",
    createdAt: new Date("2024-03-18"),
    responses: ["Chúng tôi sẽ kiểm tra tình trạng vận chuyển ngay"],
  },
  {
    id: "ticket2",
    userId: "user1",
    subject: "Sản phẩm bị lỗi",
    message: "iPhone nhận được bị lỗi speaker. Cần tư vấn bảo hành.",
    status: "in-progress",
    createdAt: new Date("2024-03-17"),
    responses: ["Chúng tôi sẽ sắp xếp lấy lại sản phẩm", "Vui lòng chuẩn bị sản phẩm"],
  },
  {
    id: "ticket3",
    userId: "user1",
    subject: "Yêu cầu hoàn tiền",
    message: "Tôi muốn hoàn tiền cho đơn hàng #order3",
    status: "open",
    createdAt: new Date("2024-03-16"),
    responses: [],
  },
  {
    id: "ticket4",
    userId: "user1",
    subject: "Khó khăn với tài khoản",
    message: "Không thể đăng nhập vào tài khoản của tôi",
    status: "closed",
    createdAt: new Date("2024-03-10"),
    responses: ["Đã giúp bạn reset mật khẩu thành công"],
  },
  {
    id: "ticket5",
    userId: "user1",
    subject: "Sản phẩm không giống hình ảnh",
    message: "Màu sắc sản phẩm khác với ảnh trên website",
    status: "open",
    createdAt: new Date("2024-03-14"),
    responses: [],
  },
]

export const mockUsers: User[] = [
  {
    id: "user1",
    email: "user@example.com",
    name: "Minh Nguyen",
    phone: "0901234567",
    role: "user",
    avatar: "/placeholder-user.jpg",
    createdAt: new Date("2024-01-15"),
    isVerified: true,
  },
  {
    id: "staff1",
    email: "staff@example.com",
    name: "Jane Smith",
    phone: "0987654321",
    role: "staff",
    avatar: "/placeholder-user.jpg",
    createdAt: new Date("2024-01-10"),
    isVerified: true,
  },
  {
    id: "admin1",
    email: "admin@example.com",
    name: "Admin User",
    phone: "0999999999",
    role: "admin",
    avatar: "/placeholder-user.jpg",
    createdAt: new Date("2024-01-01"),
    isVerified: true,
  },
]

export const mockProducts: Product[] = [
  {
    id: "prod1",
    name: "iPhone 15 Pro Max",
    slug: "iphone-15-pro-max",
    brand: "Apple",
    category: "Smartphones",
    price: 34990000,
    originalPrice: 39990000,
    description:
      "iPhone 15 Pro Max với chip A17 Pro mạnh mẽ, camera 48MP độc đáo, thiết kế titan premium, màn hình Super Retina XDR 6.7 inch, và pin vượt trội. Khám phá công nghệ iPhone tiên tiến nhất.",
    images: [
      "/iphone-15-pro-front.jpg",
      "/iphone-15-pro-back.jpg",
      "/iphone-15-pro-side.jpg",
      "/iphone-15-pro-gold.jpg",
    ],
    rating: 4.8,
    reviews: 542,
    stock: 50,
    variants: [
      { id: "var1", color: "Space Black", sku: "IP15PM-SB-256", stock: 20 },
      { id: "var2", color: "Silver", sku: "IP15PM-SV-256", stock: 15 },
      { id: "var3", color: "Gold", sku: "IP15PM-GD-256", stock: 15 },
    ],
    specs: {
      Display: '6.7" Super Retina XDR',
      Processor: "Apple A17 Pro",
      Storage: "256GB",
      Camera: "48MP Main + 12MP Ultra Wide + 12MP Telephoto",
      "Video Recording": "8K at 24/25/30fps",
      Battery: "4685 mAh",
      "Water Resistance": "IP68 (6m, 30 min)",
      Weight: "225g",
    },
  },
  {
    id: "prod2",
    name: "Samsung Galaxy S24 Ultra",
    slug: "samsung-galaxy-s24-ultra",
    brand: "Samsung",
    category: "Smartphones",
    price: 28990000,
    originalPrice: 32990000,
    description:
      "Galaxy S24 Ultra - Thiết bị thông minh nhất với AI Galaxy, camera 200MP, màn hình 6.8 inch Dynamic AMOLED 2X, chip Snapdragon 8 Gen 3. Sức mạnh và công nghệ hàng đầu trong tay bạn.",
    images: ["/samsung-s24-ultra-front.jpg", "/samsung-s24-ultra-back.jpg", "/samsung-s24-ultra.jpg"],
    rating: 4.7,
    reviews: 456,
    stock: 35,
    variants: [
      { id: "var4", color: "Phantom Black", sku: "SGS24U-PB-256", stock: 15 },
      { id: "var5", color: "Gray", sku: "SGS24U-GR-256", stock: 20 },
    ],
    specs: {
      Display: '6.8" Dynamic AMOLED 2X',
      Processor: "Snapdragon 8 Gen 3",
      RAM: "12GB",
      Storage: "256GB",
      Camera: "200MP Main + 50MP Ultra Wide + 10MP + 10MP Telephoto",
      "Video Recording": "8K at 30fps",
      Battery: "5000 mAh",
      "Water Resistance": "IP68 (1.5m, 30 min)",
      Weight: "232g",
    },
  },
  {
    id: "prod3",
    name: 'iPad Pro 12.9"',
    slug: "ipad-pro-12-9",
    brand: "Apple",
    category: "Tablets",
    price: 26990000,
    originalPrice: 29990000,
    description:
      "iPad Pro 12.9 inch với chip M4 siêu mạnh, màn hình Liquid Retina XDR, Pencil Pro tương thích, và khả năng làm việc chuyên nghiệp. Công cụ hoàn hảo cho các chuyên gia sáng tạo.",
    images: ["/ipad-pro-display.jpg", "/ipad-pro-m4.jpg", "/ipad-pro-back.jpg"],
    rating: 4.9,
    reviews: 678,
    stock: 28,
    variants: [
      { id: "var6", color: "Space Black", sku: "IPP129-SB-512", stock: 14 },
      { id: "var7", color: "Silver", sku: "IPP129-SV-512", stock: 14 },
    ],
    specs: {
      Display: '12.9" Liquid Retina XDR',
      Processor: "Apple M4",
      RAM: "16GB",
      Storage: "512GB",
      Ports: "Thunderbolt/USB-C",
      Speakers: "4 speakers",
      Battery: "10,596 mAh",
      "Water Resistance": "IPX4",
      Weight: "582g",
    },
  },
  {
    id: "prod4",
    name: "Samsung Galaxy Tab S9",
    slug: "samsung-galaxy-tab-s9",
    brand: "Samsung",
    category: "Tablets",
    price: 17990000,
    originalPrice: 19990000,
    description:
      "Galaxy Tab S9 - Máy tính bảng mạnh mẽ với màn hình 11 inch Dynamic AMOLED 2X 90Hz, chip Snapdragon 8 Gen 2, S Pen tích hợp, và pin 13,050 mAh.",
    images: ["/placeholder.jpg"],
    rating: 4.6,
    reviews: 389,
    stock: 22,
    variants: [
      { id: "var8", color: "Graphite", sku: "SGT9-GR-256", stock: 11 },
      { id: "var9", color: "Silver", sku: "SGT9-SV-256", stock: 11 },
    ],
    specs: {
      Display: '11" Dynamic AMOLED 2X',
      "Refresh Rate": "90Hz",
      Processor: "Snapdragon 8 Gen 2",
      RAM: "8GB",
      Storage: "256GB",
      Camera: "13MP Main + 8MP Ultra Wide",
      Battery: "13050 mAh",
      Speakers: "Quad speakers",
      Weight: "500g",
    },
  },
  {
    id: "prod5",
    name: "Sony WH-1000XM5 Headphones",
    slug: "sony-wh-1000xm5",
    brand: "Sony",
    category: "Accessories",
    price: 8990000,
    originalPrice: 10990000,
    description:
      "Tai nghe chống ồn hàng đầu Sony WH-1000XM5 với công nghệ Multipoint Connection, pin 30 giờ, đệm tai êm ái, và âm thanh studio chất lượng cao.",
    images: ["/placeholder.jpg"],
    rating: 4.8,
    reviews: 823,
    stock: 67,
    variants: [
      { id: "var10", color: "Black", sku: "SONY-WH-BK-001", stock: 34 },
      { id: "var11", color: "Silver", sku: "SONY-WH-SV-001", stock: 33 },
    ],
    specs: {
      "Driver Size": "30mm",
      "Frequency Range": "4Hz-40kHz",
      "Battery Life": "8 hours (30 with case)",
      "Noise Cancellation": "Industry Leading - 8 microphones",
      Weight: "250g",
      Connectivity: "Bluetooth 5.3",
      "Touch Controls": "Gesture recognition",
      Multipoint: "Connect 2 devices simultaneously",
    },
  },
  {
    id: "prod6",
    name: "Apple AirPods Pro 2",
    slug: "apple-airpods-pro-2",
    brand: "Apple",
    category: "Accessories",
    price: 5990000,
    originalPrice: 6990000,
    description:
      "AirPods Pro 2 với chống ồn chủ động hiện đại, âm thanh Adaptive Audio, Conversation Awareness, pin 30 giờ với hộp sạc, và tích hợp H2 chip.",
    images: ["/airpods-pro-2.jpg", "/airpods-pro-charging.jpg"],
    rating: 4.7,
    reviews: 1234,
    stock: 89,
    variants: [
      { id: "var12", color: "White", sku: "APP2-WH-001", stock: 45 },
      { id: "var13", color: "Black (Sport)", sku: "APP2-BK-001", stock: 44 },
    ],
    specs: {
      "Driver Size": "Custom Apple drivers",
      "Frequency Range": "20Hz-20kHz",
      "Battery Life": "6 hours (30 with case)",
      "Noise Cancellation": "Adaptive Audio + Conversation Awareness",
      "Water Resistance": "IP54",
      Weight: "4.3g per earbud",
      Chip: "H2 chip",
      Connectivity: "Bluetooth 5.3",
    },
  },
  {
    id: "prod7",
    name: 'MacBook Pro 16" M3 Max',
    slug: "macbook-pro-16-m3-max",
    brand: "Apple",
    category: "Computers",
    price: 64990000,
    originalPrice: 74990000,
    description:
      "MacBook Pro 16 inch với chip M3 Max, màn hình Liquid Retina XDR, GPU 40 lõi, pin 22 giờ, thiết kế Unibody aluminium, và port Thunderbolt 4.",
    images: ["/macbook-pro-display.jpg", "/macbook-pro-m4.jpg", "/macbook-pro-side.jpg"],
    rating: 4.9,
    reviews: 567,
    stock: 15,
    variants: [
      { id: "var14", color: "Space Black", sku: "MBP16-SB-1T", stock: 8 },
      { id: "var15", color: "Silver", sku: "MBP16-SV-1T", stock: 7 },
    ],
    specs: {
      Display: '16" Liquid Retina XDR (3456x2234)',
      Processor: "Apple M3 Max (12-core CPU, 18-core GPU)",
      RAM: "36GB unified memory",
      Storage: "1TB SSD",
      Battery: "Up to 22 hours",
      Ports: "3x Thunderbolt 4, HDMI, SD card",
      Weight: "2.15 kg",
      "Touch ID": "Yes",
    },
  },
  {
    id: "prod8",
    name: "Dell XPS 15",
    slug: "dell-xps-15",
    brand: "Dell",
    category: "Computers",
    price: 42990000,
    originalPrice: 49990000,
    description:
      "Dell XPS 15 với Intel Core i9, GPU RTX 4060, màn hình 4K OLED 15.6 inch, 32GB RAM, SSD 1TB, trọng lượng nhẹ 1.79kg - Laptop cao cấp cho professionals.",
    images: ["/placeholder.jpg"],
    rating: 4.6,
    reviews: 412,
    stock: 18,
    variants: [
      { id: "var16", color: "Platinum", sku: "DXPS15-PT-1T", stock: 9 },
      { id: "var17", color: "Graphite", sku: "DXPS15-GR-1T", stock: 9 },
    ],
    specs: {
      Display: '15.6" 4K OLED (3840x2400)',
      Processor: "Intel Core i9-13900H",
      GPU: "RTX 4060",
      RAM: "32GB",
      Storage: "1TB SSD",
      Battery: "Up to 13 hours",
      Weight: "1.79 kg",
      Ports: "2x Thunderbolt 4, USB-A, SD card",
      "Cooling System": "Vapor chamber",
    },
  },
  {
    id: "prod9",
    name: "Xiaomi 14 Ultra",
    slug: "xiaomi-14-ultra",
    brand: "Xiaomi",
    category: "Smartphones",
    price: 19990000,
    originalPrice: 22990000,
    description:
      "Xiaomi 14 Ultra với camera Leica tứ phương, chip Snapdragon 8 Gen 3, màn hình 6.73 inch AMOLED 120Hz, pin 5000 mAh, sạc nhanh 90W.",
    images: ["/placeholder.jpg"],
    rating: 4.7,
    reviews: 334,
    stock: 44,
    variants: [
      { id: "var18", color: "Black", sku: "XM14U-BK-512", stock: 22 },
      { id: "var19", color: "Silver", sku: "XM14U-SV-512", stock: 22 },
    ],
    specs: {
      Display: '6.73" AMOLED 120Hz',
      Processor: "Snapdragon 8 Gen 3",
      RAM: "16GB",
      Storage: "512GB",
      Camera: "50MP Leica with OIS",
      Battery: "5000 mAh",
      Charging: "90W HyperCharge",
      Dimensions: "162.97 x 74.54 x 8.05 mm",
      Weight: "221g",
    },
  },
]

export const mockPromotions: Promotion[] = [
  {
    id: "promo1",
    title: "Summer Sale - Up to 30% Off",
    description: "Limited time summer promotion on selected items",
    discount: 30,
    code: "SUMMER30",
    startDate: new Date("2024-06-01"),
    endDate: new Date("2024-08-31"),
  },
  {
    id: "promo2",
    title: "New Year Mega Sale",
    description: "Start the new year with amazing deals",
    discount: 25,
    code: "NEWYEAR25",
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-01-31"),
  },
  {
    id: "promo3",
    title: "Black Friday - Up to 50% Off",
    description: "Biggest sale of the year",
    discount: 50,
    code: "BLACKFRI50",
    startDate: new Date("2024-11-24"),
    endDate: new Date("2024-11-30"),
  },
]

export const mockComments: Comment[] = [
  {
    id: "com1",
    userId: "user1",
    userName: "Minh Nguyen",
    productId: "prod1",
    rating: 5,
    text: "Điện thoại tuyệt vời! Chất lượng ảnh tuyệt vời, pin khỏe, hiệu năng mạnh mẽ. Rất hài lòng với mua hàng này.",
    createdAt: new Date("2024-03-10"),
    helpful: 24,
  },
  {
    id: "com2",
    userId: "user2",
    userName: "Jane Johnson",
    productId: "prod1",
    rating: 4,
    text: "Rất tốt nhưng giá hơi cao. Tuy nhiên hiệu năng và chất lượng xứng đáng.",
    createdAt: new Date("2024-03-12"),
    helpful: 15,
  },
  {
    id: "com3",
    userId: "user1",
    userName: "Minh Nguyen",
    productId: "prod5",
    rating: 5,
    text: "Tai nghe tốt nhất tôi từng dùng! Chống ồn hoàn hảo, âm thanh sắc nét.",
    createdAt: new Date("2024-02-28"),
    helpful: 34,
  },
  {
    id: "com4",
    userId: "user3",
    userName: "Alex Chen",
    productId: "prod6",
    rating: 5,
    text: "AirPods Pro 2 là tuyệt vời. Kết nối linh hoạt với tất cả thiết bị Apple, âm thanh tuyệt vời.",
    createdAt: new Date("2024-03-05"),
    helpful: 42,
  },
  {
    id: "com5",
    userId: "user4",
    userName: "Sarah Williams",
    productId: "prod3",
    rating: 4,
    text: "iPad Pro 12.9 rất mạnh. Hoàn hảo cho công việc chỉnh sửa video.",
    createdAt: new Date("2024-02-20"),
    helpful: 18,
  },
]

export const mockOrders: Order[] = [
  {
    id: "order1",
    userId: "user1",
    items: [
      {
        productId: "prod1",
        productName: "iPhone 15 Pro Max",
        price: 34990000,
        quantity: 1,
        variantColor: "Space Black",
      },
    ],
    total: 34990000,
    status: "delivered",
    createdAt: new Date("2024-02-15"),
    shippingAddress: mockAddresses[0],
  },
  {
    id: "order2",
    userId: "user1",
    items: [
      {
        productId: "prod5",
        productName: "Sony WH-1000XM5 Headphones",
        price: 8990000,
        quantity: 1,
        variantColor: "Black",
      },
      {
        productId: "prod6",
        productName: "Apple AirPods Pro 2",
        price: 5990000,
        quantity: 1,
        variantColor: "White",
      },
    ],
    total: 14980000,
    status: "shipped",
    createdAt: new Date("2024-03-01"),
    shippingAddress: mockAddresses[0],
  },
  {
    id: "order3",
    userId: "user1",
    items: [
      {
        productId: "prod3",
        productName: 'iPad Pro 12.9"',
        price: 26990000,
        quantity: 1,
        variantColor: "Space Black",
      },
    ],
    total: 26990000,
    status: "pending",
    createdAt: new Date("2024-03-15"),
    shippingAddress: mockAddresses[0],
  },
]

export const mockAuthTokens = {
  accessToken: "mock_access_token_12345",
  refreshToken: "mock_refresh_token_67890",
}

// Mock statistics for admin dashboard
export const mockStats = {
  revenue: [10000000, 30000000, 45000000, 50000000, 65000000, 72000000],
  orders: 1250,
  products: 48,
  users: 3420,
  topProducts: [
    "iPhone 15 Pro Max",
    "Samsung Galaxy S24 Ultra",
    "Apple AirPods Pro 2",
    "Sony WH-1000XM5",
    "iPad Pro 12.9",
  ],
}

export const mockData = {
  brands: mockBrands,
  categories: mockCategories,
  addresses: mockAddresses,
  vouchers: mockVouchers,
  faqs: mockFAQs,
  supportTickets: mockSupportTickets,
  users: mockUsers,
  products: mockProducts,
  promotions: mockPromotions,
  comments: mockComments,
  orders: mockOrders,
  stats: mockStats,
}
